apiVersion: apps/v1
kind: Deployment
metadata:
  name: hook-scheduler-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: hook-scheduler
  template:
    metadata:
      labels:
        app: hook-scheduler
    spec:
      containers:
      - name: hook-scheduler
        image: hook-scheduler-image:latest
        # This field is used to specify when Kubernetes should pull images from a registry
        # For locally built images you don't need this field
        # image: your-docker-registry/publisher-image:latest  # Replace with your image URL
        # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        env:
          - name: AWS_CONFIG_PROFILE
            valueFrom:
              secretKeyRef:
                name: awsconfig-secret
                key: AWS_CONFIG_PROFILE
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                name: rabbitmqurl-secret
                key: RABBITMQ_URL
          - name: RABBITMQ_QUEUE
            valueFrom:
              secretKeyRef:
                name: rabbitmqqueue-secret
                key: RABBITMQ_QUEUE
          - name: DYNAMODB_QUEUE_TABLE
            valueFrom:
              secretKeyRef:
                name: dynamodbqueuetable-secret
                key: DYNAMODB_QUEUE_TABLE
        ports:
        - containerPort: 8082  # The port your Publisher service listens on
