apiVersion: v1
kind: Service
metadata:
  name: hook-scheduler-service
spec:
  selector:
    app: hook-scheduler
  ports:
    - protocol: TCP
      port: 8082  # The port you want to expose on the service
      targetPort: 8082  # The port your microservice listens on in the container
  type: LoadBalancer  # Use NodePort or ClusterIP as needed
